spring.application.name=queue-monitor

app.cors.allowed-origins=http://localhost:5173

simulation.max-workers=100
simulation.max-queue-capacity=1000
simulation.worker-interval=1s
simulation.metrics-interval=1s

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
